Add support for linp.sensor_occupy.es3
AlexxIT/XiaomiGateway3 pull request #1503
Opened 2024-11-29 08:01 UTC by kei81131

https://home.miot-spec.com/spec/linp.sensor_occupy.es3

![image](https://github.com/user-attachments/assets/2c8338b8-f67b-45f2-aaab-750954d1c988)

2024-11-29 09:45 UTC, CharmingCheung requested changes
Linptech ES3 is `linp.sensor_occupy.es2`. You can check the instruction manual at this URL: https://home.mi.com/views/introduction.html?model=linp.sensor_occupy.es2

2024-11-29 09:45 UTC, CharmingCheung commented on custom_components/xiaomi_gateway3/core/devices.py
> +        BaseConv("battery", "sensor", mi="3.p.1003"),
```suggestion
        BaseConv("battery", "sensor", mi="4.p.1003", entity=ENTITY_LAZY),
```

2024-11-29 09:45 UTC, CharmingCheung commented on custom_components/xiaomi_gateway3/core/devices.py
> +    20731: ["Linp", "Occupancy Sensor", "ES3", "linp.sensor_occupy.es3"],
```suggestion
    20731: ["Linptech", "Human Presence Sensor ES3", "ES3BB", "linp.sensor_occupy.es2"],
```

2024-11-29 09:45 UTC, CharmingCheung commented on custom_components/xiaomi_gateway3/core/devices.py
> +    # https://home.miot-spec.com/spec/linp.sensor_occupy.es3
```suggestion
    # https://home.miot-spec.com/spec/linp.sensor_occupy.es3
    # https://home.mi.com/views/introduction.html?model=linp.sensor_occupy.es2
```

2024-12-25 13:24 UTC, merged

2024-12-25 13:24 UTC, AlexxIT commented
Thanks!

2024-12-28 12:12 UTC, AlexxIT commented
https://github.com/AlexxIT/XiaomiGateway3/releases/tag/v4.0.8